### ISSUE TITLE
target: mbedos5: source/pins.cpp is no longer generated against mbed OS 5.2

### ISSUE THREAD

**Issue by janjongboom** [jerryscript-project/jerryscript#1493]
Go to build/jerryscript/targets/mbedos5, then run `make source/pins.cpp`.

This fails, because the `Target` constructor has been removed in mbed OS 5.2 now; which is used in https://github.com/jerryscript-project/jerryscript/blob/master/targets/mbedos5/tools/generate_pins.py.

**Comment by theotherjimmy** [comment]
The `Target` constructor has been replaced by `target` from `tools/targets.json` it should have the same signature.

**Comment by theotherjimmy** [comment]
I take it back. What you want is `Target.get_target`
