### ISSUE TITLE
Hang in Date constructor

### ISSUE THREAD

**Issue by renatahodovan** [jerryscript-project/jerryscript#1657]
###### Jerry version:

```
Checked revision: b140158
Build: debug.linux
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:
Running this test cases lasts unexpectedly long (killed after 2 minutes):

```javascript
new Date(-565224, 1)
```

###### Build command:
```
./tools/build.py --debug --clean
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

**Comment by akosthekiss** [comment]
Because the root cause is how negative years are handled, the following expressions cause the same infinite wait:

```javascript
new Date().setFullYear(-565224);
new Date().setUTCFullYear(-565224);
new Date().setYear(-565224);
Date.UTC(-565224, 1);
```
