### ISSUE TITLE
Nominating Jan Jongboom (@janjongboom) to become a JerryScript committer and mbed port reviewer

### ISSUE THREAD

**Issue by zherczeg** [jerryscript-project/jerryscript#1673]
Hi,

Jan did an excellent work on porting and maintaining JerryScript on the ARM Mbed OS so I would like to nominate him to become a committer for JerryScript and reviewer for the Mbed port.

His patches are:

#1531 target: mbedos5: Change to debug profiles
#1522 target: mbedos5: Support for building on Windows
#1518 target: mbedos5: Sort magic strings
#1512 target: mbedos5: mbed CLI refuses to build if no .mbed file present
#1494 target: mbedos5: Update generate_pins.py
#1485 target: mbedos5: Define JERRY_JS_PARSER macro
#1468 target: mbedos5: Update to mbed OS 5.2.3
#1458 target: mbedos5: Allow jerry_port_console and jerry_port_log to be overriden by user code
#1457 target: mbedos5: Add return value to setTimeout/setInterval and implement clearTimeout/clearInterval
#1455 target: mbedos5: Add PwmOut and AnalogIn interfaces
#1427 target: mbedos5: Add carriage return in jerry_port_console

Any seconds?

**Comment by akosthekiss** [comment]
+1

**Comment by jiangzidong** [comment]
+1

**Comment by yichoi** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by robertsipka** [comment]
+1

**Comment by martijnthe** [comment]
+1 (don't know if my vote has any meaning ;))

**Comment by bzsolt** [comment]
+1

**Comment by akosthekiss** [comment]
Congrats to the successful nomination, @janjongboom!

**Comment by janjongboom** [comment]
![Yes](http://i.amz.mshcdn.com/hnZsO4gromEP7Y2rfsFf_qrN7is=/fit-in/850x850/http%3A%2F%2Fmashable.com%2Fwp-content%2Fgallery%2Ftriumph%2Fnapoleon-dynamite.gif)
