### ISSUE TITLE
ES6 Promise

### ISSUE THREAD

**Issue by martijnthe** [jerryscript-project/jerryscript#1675]
As mentioned on the JerryScript mailing list: @jiangzidong and myself will be working on adding ES6 Promise to JerryScript. I'm opening this ticket just to track the fact that we are working on this.

@jiangzidong FYI:
> this is my dev branch: https://github.com/LaszloLango/jerryscript/tree/promise-dev
> It is not much, but might save some time for you.
>
> Regards,
> László

**Comment by jiangzidong** [comment]
Promise Implementation depends on the Job queue. So I first sumbit the job queue PR #1685 
Then I will work on the Promise

**Comment by jiangzidong** [comment]
TODO list of promise

- [ ] jobqueue

- [ ] basic promsie (constructor and then)

- [ ] full promise
