### ISSUE TITLE
JerryScript community call 5 April

### ISSUE THREAD

**Issue by janjongboom** [jerryscript-project/jerryscript#1706]
Hi,

For those of you who *do* read the GitHub issues but are not on the [mailing list](https://mail.gna.org/listinfo/jerryscript-dev):

We are planning the first JerryScript community call on Wednesday 5 April, 10:00 CET / 18:00 Korea / 17:00 China / 09:00 UK time. It's a chance to meet fellow contributors and discuss the plans we have with JerryScript. There's no set agenda for the first call.

To join, just go to this Google Hangout: https://hangouts.google.com/call/fwivajpnavhn7j64wiknjo7tvqe

Hope to see you all on Wednesday!

**Comment by jiangzidong** [comment]
I will join in :) See you on Wednesday
