### ISSUE TITLE
Use GitHub ribbon

### ISSUE THREAD

**Issue by polaroi8d** [jerryscript-project/jerryscript#1709]
In the most GitHub project website use the "Fork me on GitHub" ribbon. In my opinion this is a good proposer to check our repository. So we can change the "View on GitHub" menu for this, but first I want to ask the community about it. 

If you don't know about ribbons check [this](https://github.com/blog/273-github-ribbons).

**Comment by LaszloLango** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by robertsipka** [comment]
+1

**Comment by jiangzidong** [comment]
+1

**Comment by polaroi8d** [comment]
Opened the following PR #1712 for it

**Comment by akosthekiss** [comment]
Closing as #1712 has landed
