### ISSUE TITLE
JerryScript Development Roadmap?

### ISSUE THREAD

**Issue by rwaldron** [jerryscript-project/jerryscript#1735]
[This conversation](https://github.com/01org/zephyr.js/issues/852) prompted me to wonder about the roadmap of JerryScript. I remember that Samsung representatives joined us at a TC39 meeting in 2014 and explained that the goal was to create an ES5.1 subset, but it appears that ES2015 features have also been added (which is good!). 

Anyway, I'm wondering if there is a published document that describes the long term goals, or a roadmap of some sort. Thanks in advance! :)

**Comment by yichoi** [comment]
This could be one of discussion item of community call.
