### ISSUE TITLE
Denial of Service: Null Pointer De-reference

### ISSUE THREAD

**Issue by JeffJerseyCow** [jerryscript-project/jerryscript#1821]
I've discovered a NULL pointer de-reference condition within Jerryscript.

If the bytes - "0x27 0x5c 0xe2 0x80 0xa8 0x27 0x41" are evaluated by jerry_eval a segmentation fault will occur resulting in a denial of service.

It occurs within jmem_heap_free_block when block_p->size is de-referenced.

**Proof**
![image](https://cloud.githubusercontent.com/assets/25182776/26021655/38ac0afc-378a-11e7-865e-f74c0c951822.png)

The call tree is as follows (generally):
1. jerry_eval
2. ecma_op_eval_chars_buffer
3. parser_parse_script
4. parser_parse_source
5. lexer_next_token (parses the source for strings and returns)
6. parser_parse_statements (throws a parsing error via parser_raise_error and returns to the parser_parse_source PARSER_CATCH statement)
7. parser_free_literals
8. util_free_literal
9. jmem_heap_free_block (SEGMENTATION FAULT)

**Comment by LaszloLango** [comment]
@JeffJerseyCow thanks for the bug report and sorry for the late answer. I can confirm this is a valid bug. We'll fix it.
