### ISSUE TITLE
Heap Buffer Over-read  in skip_space

### ISSUE THREAD

**Issue by JeffJerseyCow** [jerryscript-project/jerryscript#1867]
Within the function skip_spaces, js-lexer.c:218 – a buffer over-read occurs when looking for the bytes 0xe2 0x80 0xa9, paragraph separator, by attempting a read ahead. There is an assert on line 217 that would prevent this in debug mode. Is the idea to let bugs into release builds? Or is there an over-sight I’m not seeing?

**Comment by zherczeg** [comment]
In JerryScript it is the user responsibility to pass valid UTF8/CESU8 data to the engine. If the user does not trust the input, they can use `jerry_is_valid_utf8_string` and `jerry_is_valid_cesu8_string` to check it. If these functions returns with `false`, the user should trow an error.

Overall this is a performance optimization for trusted input.

**Comment by LaszloLango** [comment]
Fixed
