### ISSUE TITLE
ES2015 or ES2017 for new ArrayBuffer(length)

### ISSUE THREAD

**Issue by glistening** [jerryscript-project/jerryscript#1962]
The definition of `new ArrayBuffer(length)` is changed in ES2017. 
 
( I pushed #1959 before I recognise it. I would like to get opinions. )

For example,

`ES2015`
_new ArrayBuffer(1.1)_ should throw RangeError.

`ES2017`
_new ArrayBuffer(1.1)_ creates ArrayBuffer with byteLength=1.

I would like to follow ES2017's definition.

Major engines (v8/spidermonkey/jsc) already work like ES2017 spec. ( Or ES specification may be updated to follow major engines.  [ES2016](https://www.ecma-international.org/ecma-262/7.0/index.html#sec-arraybuffer-length) specification was same to ES2015. ).

**Comment by jiangzidong** [comment]
I prefer following ES2017 if there are some conflict with ES2015, since that is major engines' choice.

Maybe we should change the profile name `es2015-subset` to `es2017-subset` ?

**Comment by glistening** [comment]
@jiangzidong Thank you for opinion. I also thought that `es2015-subset` is correct name if we follow latest specification like new ArrayBuffer(length). However, ES specification will be changed for several forthcoming years ( es2018, es2019, ... ), and there may be feature X, Y,  that major specification follows es2015 yet. I cannot find good name that covers this situation. So I would like to keep the current name - `es2015-subset`.

**Comment by jiangzidong** [comment]
Yes, make sense.
