### ISSUE TITLE
Does jerryscipt support Websockets JS library?

### ISSUE THREAD

**Issue by Ash200012** [jerryscript-project/jerryscript#2029]
I am trying to take my javascript code (previously run in a browser) and run it from jerryscript. My JS code uses websockets libraries. Does jerryscript support this or any other network protocol library?

**Comment by zherczeg** [comment]
JerryScript is a JS engine, not an environment like node.js. There are several other projects, such as https://github.com/Samsung/iotjs which provides network communication on the top of jerryscript.

**Comment by Ash200012** [comment]
Thank you for your reply. IoTjs seems to have limited platform support..are there any other projects on top of jerryscript or not that have network communication support?

**Comment by zherczeg** [comment]
Maybe MBED or Zephyr has them.

**Comment by zherczeg** [comment]
Btw what is your platform?

**Comment by Ash200012** [comment]
ARM boxes and potentially MIPS. I am looking for a very low footprint JS engine where I can write a JS websocket or http server that can do things like discovery, send/receive messages in JSON format, and even do downloading of files.

**Comment by zherczeg** [comment]
I mean your OS

**Comment by Ash200012** [comment]
Many flavors of custom linux..busybox linux, etc. python may not be available on them

**Comment by zherczeg** [comment]
IoT.js runs on any Linux (only a basic libc required), no need any python (except for compiling, but you can cross compile on desktop).

**Comment by Ash200012** [comment]
OK thanks I will look into it if it is my only option.

**Comment by akosthekiss** [comment]
Closing as WebSockets is out of scope for the engine and discussion is continued at the issue tracker of IoT.js (https://github.com/Samsung/iotjs/issues/1241).
