### ISSUE TITLE
How To Force Garbage Collection

### ISSUE THREAD

**Issue by natewatson999** [jerryscript-project/jerryscript#2062]
Is there a Javascript interface to force Garbage Collection to happen in Jerryscript? I know there's a way to do it from the C perspective, but I can't find a way to do it in JS.

Other JS environments have ways to force garbage collection in JS. Opera's window.opera.collect() and Node's global.gc() are two examples. Does this concept exist in Jerryscript?

**Comment by LaszloLango** [comment]
@natewatson999, yes, http://jerryscript.net/api-reference/#jerry_gc

**Comment by LaszloLango** [comment]
@natewatson999 if you would like to call it from JavaScript, than you need this: http://jerryscript.net/ext-reference-handler/#jerryx_handler_gc

**Comment by galpeter** [comment]
By default the jerry library does not expose the gc api to the JS side, you'll need to expose the C gc API method by registering it to the JS context (as described by @LaszloLango) in your application.

**Comment by akosthekiss** [comment]
@natewatson999 Did any of the above help/work for you? Please close the issue if your question has been answered.

**Comment by natewatson999** [comment]
I am testing it out now. It may take a little while to be sure because I'm new to Jerryscript & I'm having to figure this out for something that is a bit of an edge case. I should be able to close this or report if it works by tomorrow though.

**Comment by natewatson999** [comment]
I think I have it working. Thank you all.
