### ISSUE TITLE
Add `jerryx_arg_utf8_string` to jerryx arg.h utility

### ISSUE THREAD

**Issue by martijnthe** [jerryscript-project/jerryscript#2132]
The current `jerryx_arg_string` ends up in a call into `jerry_string_to_char_buffer`.
That function writes the string using the internal CESU-8 encoding.
I'd be good to have a variant of this that uses UTF-8 encoding instead.

**Comment by martijnthe** [comment]
cc @jiangzidong could you add this? Thanks!

**Comment by jiangzidong** [comment]
Sure :)

**Comment by galpeter** [comment]
AFAIK, this is now in the master. I'll close it.
