### ISSUE TITLE
JerryScript 2.0

### ISSUE THREAD

**Issue by zherczeg** [jerryscript-project/jerryscript#2213]
It would be good to release JerryScript 2.0 this year. No specific deadline so far.

What we should do before that is reworking the API. Some ideas:

- delete obsolote functions
- rework error flag to be an error value (error can only be a result of something, and cannot be used as input except unboxing its value).

**Comment by martijnthe** [comment]
> delete obsolote functions

Which ones are those?

Quick search for "deprecated" through the code base revealed:
```
JERRY_DEPRECATED_API
bool jerry_get_object_native_handle (const jerry_value_t obj_val, uintptr_t *out_handle_p);
JERRY_DEPRECATED_API
void jerry_set_object_native_handle (const jerry_value_t obj_val, uintptr_t handle_p,
                                     jerry_object_free_callback_t freecb_p);
```

```
#pragma message ("using jerry-api.h directly is deprecated, please use jerryscript.h")
```

```
#pragma message ("using jerry-port.h directly is deprecated, please use jerryscript-port.h")
```

```
  JERRY_INIT_MEM_STATS_SEPARATE  = (1u << 3), /**< deprecated, an unused placeholder now */
  JERRY_INIT_DEBUGGER            = (1u << 4), /**< deprecated, an unused placeholder now */
```

Anything else (other than the "old"/current error flag APIs)?

**Comment by zherczeg** [comment]
Mostly these. Maybe the parse variant where the source is not provided, but that is not necessary. We should emphasize that pass source info if available, and pass NULL if not.

It will be a much smaller scope API rework that JerryScript 1.0.

**Comment by galpeter** [comment]
I've got a few suggestions for extra API functions/improvements:
* JSON C API - parse/stringify
* Regex construction from API / maybe even exec/test
* Allow jerry_is_feature_enabled to query builtin/es2015-subset objects
* Add DataView for es2015-subset

please note I'm not sure how widely they would be used or needed.

**Comment by galpeter** [comment]
(IMHO) If we want to remove functions we should mark them as obsolete as a first step. This way we can (hopefully) notify the users that there will be a bigger change. Related to this I think we should consider writing a migration guide or at least a change list between v1 and v2.

**Comment by zherczeg** [comment]
Snapshot generation API  rework #2259

Lets just collect the API rework patches here, and later we can write a changelog using these references.

**Comment by zherczeg** [comment]
Snapshot executing API rework #2270

**Comment by zherczeg** [comment]
Jerry parse rework: #2282

**Comment by imiklos** [comment]
Rename the jerry_value_has_error_flag function: [#2290](https://github.com/jerryscript-project/jerryscript/pull/2290)

**Comment by imiklos** [comment]
Rename the `jerry_value_has_abort_flag` function [#2291](https://github.com/jerryscript-project/jerryscript/pull/2291)

**Comment by imiklos** [comment]
Rename the `jerry_value_clear_error_flag` function [#2292](https://github.com/jerryscript-project/jerryscript/pull/2292)

**Comment by imiklos** [comment]
Rename the `jerry_value_set_error_flag` function [#2293](https://github.com/jerryscript-project/jerryscript/pull/2293)

**Comment by imiklos** [comment]
Rename the `jerry_value_set_abort_flag` function [#2294](https://github.com/jerryscript-project/jerryscript/pull/2294)

**Comment by imiklos** [comment]
Rename the `jerry_get_value_without_error_flag` function [#2295](https://github.com/jerryscript-project/jerryscript/pull/2295)

**Comment by zherczeg** [comment]
Replace the jerry_value_set_error_flag function with jerry_create_error_from_value #2367

**Comment by zherczeg** [comment]
Add operational mode for jerry_gc API call. #2385

**Comment by imiklos** [comment]
Replace jerry_value_set_abort_flag with jerry_create_abort_from_value [#2411](https://github.com/jerryscript-project/jerryscript/pull/2411)

**Comment by lygstate** [comment]
would 2.0 be a LTS version?

**Comment by zherczeg** [comment]
Remove jerry_get_arg_value auto-conversion function: #2425

**Comment by zherczeg** [comment]
We only do backward incompatible changes before releases. So yes, after these are landed, there will be no large change for a long time.

**Comment by rerobika** [comment]
Simplify source evaluation options. #2431

**Comment by zherczeg** [comment]
Merge instance into context #2501

**Comment by wangzhikang123** [comment]
We use JerryScript in our products, and we need to rely on an officially released version. But version 1.0 is too old to meet the demand, and we expect the community to release version 2.0 as soon as possible. Do you have a release plan in the near future?

**Comment by akosthekiss** [comment]
@wangzhikang123 Admittedly, the releasing process of the project has room for improvement. But still, "expect" is a somewhat strong word. Moreover, if you are using the project in products (which is great!), don't hesitate to take part in the _public_ development of the project by contributing back improvements or outstanding bug fixes. Please, also refer to the [governance](https://github.com/pando-project/jerryscript/wiki/Governance) wiki page ("expect" vs meritocracy).

**Comment by LaszloLango** [comment]
JerryScript 2.0 is out. You can find the release here: https://github.com/jerryscript-project/jerryscript/releases/tag/v2.0
