### ISSUE TITLE
Nominating Robert Sipka (robertsipka) to become a reviewer

### ISSUE THREAD

**Issue by zherczeg** [jerryscript-project/jerryscript#2254]
I would like to nominate Robert Sipka to become a JerryScript reviewer. I trust him to follow our process. He has already nearly 60 informal reviews:

#2250 Improve jerry_is_feature_enabled with object availability information
#2245 Move the sleep function to jerry-port
#2243 Add json parse and stringify function to jerryscript c api
#2235 Eliminate early memory deallocations in case of NuttX and TizenRT
#2234 Remove ecma_get_length_string
#2225 Fix build failure of NuttX tool
#2223 Travis CI - Put the NuttX/STM32F4 job to the allowed failures section
#2218 Reduce the memory footprint of 'ecma_instantiate_builtin'
#2216 Removed 'is_static' parameter from 'BUILTIN' macro, because was never used.
#2215 Negative tests
#2207 Multiple nexts with one command
#2208 Fix '--cmake-param' option of the build script.
#2206 Update the webpage
#2201 Fix buffer overrun while parsing malformed JSON hex escape sequence
#2171 Print the return value of the engine in case of TizenRT.
#2169 Change '{' regex parsing to work similarly to other engines
#2168 Fix the endianness of EPS8266 system
#2167 Update the webpage
#2166 Add version fields for debugger configuration
#2164 Modify the build method of TizenRT target
#2161 Introduce the Array Buffer C API
#2157 Fix random number generation on ESP8266
#2155 Update Zephyr RTOS port for Zephyr 1.10 release
#2154 Modify the build method of NuttX target
#1994 Fix for toFixed method
#1825 Add `setjmp` and `longjmp` functions for tizenrt-artik05x
#1822 Use external handlers in tizenrt-artik05x target
#1817 Increase verbosity when breakpoints not found in HTML (JavaScript) Debugger client
#1816 Include jerry-ext/handler only in nuttx-stm32f4 target
#1767 Merge `lit-unicode-*.inc.h`-related generator scripts
#1753 Support ECMAScript stopping in JerryScript
#1712 Add GitHub ribbon to header.html
#1704 Fix several pylint warning in debugger python client
#1703 Bug fix for the debugger python client 'quit' command
#1687 Rename 'CONFIG_DISABLE_ARRAYBUFFER_BUILTIN' to 'CONFIG_DISABLE_ES2015_ARRAYBUFFER_BUILTIN'
#1682 Update the webpage
#1668 Style fix: return value comments
#1659 Fix several pylint warnings
#1651 Fix old-style function definitions
#1628 Add delete all breakpoints feature to debugger (javascript)
#1599 Add a port setting to build script
#1576 Add new input validator API functions
#1557 Initial version of JerryScript debugger
#1532 [ES2015][TypedArray] Add other 8 types
#1527 target: zephyr: Switch to MinSizeRel build type following mainline
#1525 Update macro definitions in Curie-BSP target
#1521 Update the webpage
#1506 [API] Improve the performance of the external magic id search
#1505 Isolate GCC specific code
#1503 Fix test-api.c
#1483 Add #if control around GCC builtin functions so that the code can be compiled using non-GCC compilers
#1476 Add feature to remove parser
#1338 Improve the linking of libraries
#1232 Adapted the makefiles to the new build system
#1212 Initial refactoring of the code to match the latest API
#1209 Fix RIOT port after API update
#1175 Update the API changes in mbed targets
#989 Add stm32f4 board to the targets

Seconds are welcome.

**Comment by yichoi** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by rtakacs** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by zherczeg** [comment]
Robert now is a reviewer! Congratulations!

**Comment by LaszloLango** [comment]
Congratulations, I've updated the wiki: https://github.com/jerryscript-project/jerryscript/wiki/Assigned-people
