### ISSUE TITLE
jerryx_arg_transform_optional does not advance iterator in case the value is undefined

### ISSUE THREAD

**Issue by martijnthe** [jerryscript-project/jerryscript#2288]
I would expect in [this line] to pop the iterator if `js_arg` is `undefined`.
Otherwise there can only be a single optional argument. Another consequence is that  `jerryx_arg_transform_optional` does not work together with `jerryx_arg_transform_object_properties` because the iterator does not get advanced when an optional arg is `undefined`...

It looks like the unit test doesn't have either of these scenarios as a test case.

@jiangzidong do you agree this is a bug?

[this line]: https://github.com/jerryscript-project/jerryscript/blob/4e7a9d2d53804c1af7f7f7c57e2f6640898d0807/jerry-ext/arg/arg-transform-functions.c#L37

**Comment by jiangzidong** [comment]
Hi @martijnthe , yes, I think it is a bug. Sorry for that.
And could you help fix it since I dont have the dev env in my hand now.
