### ISSUE TITLE
How to provide more error information?

### ISSUE THREAD

**Issue by BernardXiong** [jerryscript-project/jerryscript#2297]
In the Unix build, if there are some errors in script, only little message provided:
```JavaScript
A();
```

    ./bin/jerry error.js
    Script Error: ReferenceError

However, in iot.js, more error message provided:

    ./build/x86_64-linux/debug/bin/iotjs error.js 
    uncaughtException: ReferenceError: A is not defined

How to show this message? Thanks.

**Comment by LaszloLango** [comment]
You must turn on the error messages. They are disabled by default to save some ROM space.

`tools/build.py --error-messages=on`

Furthermore there is a new feature which recently landed into the master branch. Now you can get a backtrace too if you enable the `line-info`.

You can check the build options for details: `tools/build.py --help`
```
--error-messages X    enable error messages (ON, OFF; default: OFF)
--line-info X         provide line info (ON, OFF; default: OFF)
```

**Comment by BernardXiong** [comment]
Thank @LaszloLango 

I put JerryScript in RT-Thread as a standalone package:
https://github.com/RT-Thread-packages/jerryscript

The scons is used in RT-Thread. Therefore, I have to put a macro-definition in compiler command by myself. If I only define -DJERRY_FEATURE_ERROR_MESSAGES, it's not working. What's the correct way?

**Comment by LaszloLango** [comment]
For CMake users the following options must be used: `-DFEATURE_ERROR_MESSAGES=ON` and `-DFEATURE_LINE_INFO=ON`

**Comment by zherczeg** [comment]
Wrong macro name. It should be `JERRY_ENABLE_ERROR_MESSAGES`

**Comment by BernardXiong** [comment]
Done! Thank you very much.
