### ISSUE TITLE
Discussing error management

### ISSUE THREAD

**Issue by zherczeg** [jerryscript-project/jerryscript#2318]
There is an ongoing work of changing "error flags" to "error values". "error values" are primary values such as "null", "number", but they exist only on Jerry API level. Therefore JS do not need handle them at all.

Error values are designed to be return values, not arguments (no change here). Hence any API or C callback function can return with an error value, but the returned error value cannot be passed to other functions except a few error management functions and `jerry_release`. The value can be extracted from the error by `jerry_get_error_from_value`. The `jerry_create_error_from_value` creates an error value using the non-error value argument. For aborts, there will be a `jerry_create_abort_from_value`. Abort is the same as errors, except they are not caught by JS, and can only created by API or the debugger. `jerry_is_error_value` tells if the value is an error. Abort is considered a special variant of error. So everything true to an error is also true to an abort, but there is a special create/is_abort function to tell the difference.

This is the current plan now. We are open to feedback.

**Comment by LaszloLango** [comment]
Closing beacause this planned rework had finished a long time ago.
