### ISSUE TITLE
Does snapshot work with native functions?

### ISSUE THREAD

**Issue by jack9766** [jerryscript-project/jerryscript#2354]
If I add a native C function wrapper to the global JS scope then load and execute a snapshotted function that invoke the said native function wrapper inside its function body, will it work?

**Comment by zherczeg** [comment]
Yes, since the functions (bindings) are identified by names. Hence if a snapshot call f() function, the resolving of f happens at runtime.

**Comment by jack9766** [comment]
Nevermind the problem was the buffer size is too small.
