### ISSUE TITLE
Prevent jerry_create_string from copying string?

### ISSUE THREAD

**Issue by jack9766** [jerryscript-project/jerryscript#2358]
Is there a way to make `jerry_create_string` not duplicate the string literal instead use the same reference?

**Comment by LaszloLango** [comment]
No, it is not trivial because of the inner representation of strings.

**Comment by zherczeg** [comment]
I am not sure I fully understand your question, but do you want to "pass a `char*` pointer" to jerryscript? Currently that is only possible for ES6 buffers.

**Comment by jack9766** [comment]
Yes! How do I pass a pointer to JS?
