### ISSUE TITLE
Side effect of using uncompressed pointer?

### ISSUE THREAD

**Issue by jack9766** [jerryscript-project/jerryscript#2368]
I was wondering if there are any side effects besides increased memory usage by using uncompressed pointer(passing `--cpointer-32bit` as a build option).

My main concern is according to the [data representation](https://github.com/jerryscript-project/jerryscript/blob/master/docs/04.INTERNALS.md#data-representation) section of the docs:

![Data](https://raw.githubusercontent.com/jerryscript-project/jerryscript/master/docs/img/ecma_value.png)

the structure can only hold at max 29 bit pointers. So how would a 32 bit pointer fit in?

**Comment by LaszloLango** [comment]
`ecma_value_t` cannot contain any pointer. `ecma_value_t` and `jmem_cpointer_t` arre two different types.

**Comment by zherczeg** [comment]
with cpointer 32 bit you must use 8 byte aligned pointers. jerry allocator satisfy this requirement, and most mallocs as well. Btw the image is outdated, we use 3 bit for type now, and no error bit.

**Comment by jack9766** [comment]
The following is pulled directly from the doc:

> in case of number, string and object the value contains an encoded pointer.

Is it outdated or `ecma_value_t` does store pointers in it's value section?

I assume by "encoded" ptr they mean compressed?

**Comment by zherczeg** [comment]
Depends. On 64 it contains a 16 or 32 bit cpointer, on 32 bit it is a direct pointer.

**Comment by jack9766** [comment]
Will disabling compressed pointer lower performance? since dereferencing uncompressed ptr might take longer?

**Comment by zherczeg** [comment]
Hm? I would say the opposite.

**Comment by jack9766** [comment]
I tested with the flag on and off. It seem using uncompressed ptr increased the performance of overheads(JS calling C, C to JS, JS to JS) by 5 to 15 percent. But the performance of JS function bodies stay approximately the same.

Any explanations?
