### ISSUE TITLE
mbed-os: generate_pins.py fails if last value of PinName enum is not defined

### ISSUE THREAD

**Issue by wajahat-ublox** [jerryscript-project/jerryscript#2418]
In mbed OS, PinName enum is defined in PinNames.h file for each target. 
Considering a case where a target (e.g TARGET_HI2110) marks the last entry of the enum as NUM_MAX, the generate_pins.py reports error: IndexError: list index out of range.

**Comment by akosthekiss** [comment]
Unfortunately, this issue report hasn't been followed up. @wajahat-ublox Is this still an issue for you?

**Comment by wajahat-ublox** [comment]
@akosthekiss 
Yes problem is still there.

**Comment by akosthekiss** [comment]
cc @dbatyai @rerobika

**Comment by wajahat-ublox** [comment]
@akosthekiss 
I apologize, i was on an older revision and hence saw the problem again. I just tried with latest and problem is not reproducible. I am closing this.
