### ISSUE TITLE
The JS engine may free a literal twice if error occurs at function "parser_post_processing"

### ISSUE THREAD

**Issue by wangzhikang123** [jerryscript-project/jerryscript#2531]
The test code:
[regexp-simple-atom-and-iterations.js.txt](https://github.com/jerryscript-project/jerryscript/files/2393003/regexp-simple-atom-and-iterations.js.txt)

Compile like this:
python tools/build.py  --error-messages=ON --line-info=ON --mem-heap 9 --debug

Then there will be an assertion fail to indicate the pointer to be freed is not pointing to the heap.  

I think it's the double free of literal causing such a isuue.

First free at "js-parser.c" line 206,which is called by function "parser_post_processing" at line 1496
![1](https://user-images.githubusercontent.com/43208780/45693746-56c16600-bb90-11e8-9087-7c656af842d1.JPG)

After error occurs at line 1726 for "out of memroy" error,the second free will happen at line 2416-->line 2413-->"common.c" line 42
![2](https://user-images.githubusercontent.com/43208780/45694316-976daf00-bb91-11e8-8425-e192581819d0.JPG)
Of course,when the second free happens,the address passed to function "jmem_heap_free_block" is totally wrong as it was changed at "js-parser.c" line 201,which is the reason why the assertion fails.

**Comment by wangzhikang123** [comment]
.

**Comment by zherczeg** [comment]
Could you share a test case?

**Comment by akosthekiss** [comment]
I think that this issue has been closed by the poster as invalid (as even the original issue report text has been edited out).

**Comment by zherczeg** [comment]
Thank you for the report. It looks like a `literal_p->status_flags |= LEXER_FLAG_SOURCE_PTR;` needs to be added after the first free.

**Comment by wangzhikang123** [comment]
How about line 645 and1984
