### ISSUE TITLE
Increase branch coverage: Array.prototype routines

### ISSUE THREAD

**Issue by matedabis** [jerryscript-project/jerryscript#2721]
This issue is created in order to improve branch coverage of functions of `Array.prototype` routines.

The following script is made for testing branch coverage with all the test suites (`--jerry-test-suite --test262 --unittests --jerry-tests`), or with only one `.js` file.

https://github.com/matedabis/jerryscript/blob/gcov_coverage_tester/tests/gcov-tests/gcovtester.py

While measuring the branch coverage we dont count JERRY_ASSERT s. The results are measured by running all the test scripts, with the modifications in the PRs.

If you start working on a function, or open a PR, please leave a comment about it on this issue, so I can keep this issue up to date.

| Function | Branch coverage | Progress |
| :---         |     :---:      | :--- |
| helper set length  | 0/0       | All covered |
|  toString  | 6/6     | #2717    |
| toLocaleString     | 18/18       | #2716 |
| concat     | 11/16       | @repasics is working on it |
| get separator string   | 2/2       | All covered |
| at index   | 5/6       | @matedabis is working on it |
| join     | 20/20       | #2727  |
| pop     | 13/16       | @repasics is working on it |
| push     | 13/16       | @repasics is working on it |
| reverse     | 37/38       | #2728  |
| shift     | 22/30       | @matedabis  is working on it |
| slice     | 15/22       | @repasics  is working on it |
| sort compare helper| 20/26      | @repasics  is working on it |
| sort     | 48/48       | #2674 |
| splice     | 78/78       | #2682 |
| unshift     | 24/28       | @matedabis  is working on it |
| indexOf     | 26/26       | All covered |
| lastIndexOf     | 40/40       | All covered |
| apply     | 32/32       | All covered |
| map     |   21/22     | Remaining branch is unreachable according to us |
| filter     |   22/22     | All covered |
| reduce from    |   45/46     | Remaining branch is unreachable according to us |
| reduce    |   0/0     | All covered |
| reduce right |   0/0     | All covered |
| find     |   19/22     | @matedabis is working on it |

**Comment by rerobika** [comment]
Closing this issue since #2796 has landed.
