### ISSUE TITLE
Lookbehind not supported in regular expressions

### ISSUE THREAD

**Issue by cyongbin** [jerryscript-project/jerryscript#2900]
- Jerryscript's regular expression not support positive/negative assert, em:
```
/(?<=\?)[^#]+/
```

**Comment by LaszloLango** [comment]
JerryScript supports the positive and negative assertions in RegExp objects. Your testcase is not a valid assertion pattern.

**Comment by cyongbin** [comment]
> JerryScript supports the positive and negative assertions in RegExp objects. Your testcase is not a valid assertion pattern.

- My testcase is ok, i had test it in node.js env.
- node.js em:
```
var url =  @'http://test.com?name=tom';
var quary = url.match(/(?<=\?)[^#]+/);
   @@@console.log(quary);
```
- It can only write as below in jerry:
```
var url = 'http://test.com?name=tom';
var quary = url.match(/\?[^#]+/);
query = query ? query[0].splice(1) : null;
console.log(quary);
```

**Comment by zherczeg** [comment]
We have lookahead/lookbehind and positive/negative assertions in regexps. ES5 only supports lookahead and your pattern has lookbehind.

**Comment by cyongbin** [comment]
Thank you. I look forward to your realization of lookbehind model.

**Comment by akosthekiss** [comment]
> We have lookahead/lookbehind and positive/negative assertions in regexps. ES5 only supports lookahead and your pattern has lookbehind.

@zherczeg Does that mean that the script with this regex pattern should work if the engine is built with ES2015 profile? (<-- "We have ... lookbehind" + "ES5 only supports lookahead" + "your pattern has lookbehind")

**Comment by zherczeg** [comment]
Lookbehind is introduced in ES2018:
https://www.ecma-international.org/ecma-262/9.0/#prod-Assertion

Was not in ES2017:
https://www.ecma-international.org/ecma-262/8.0/#prod-Assertion

So only ES2018 compatible engines should support it.

**Comment by akosthekiss** [comment]
I've edited the issue title to be more to the point. I'm also marking the issue as a feature request but closing it at the same time as ES8/9 is out of scope for the project for now. We should get full ES6 support landed first.
