### ISSUE TITLE
An error should be thrown when defining a property for a read-only variable in strict mode.

### ISSUE THREAD

**Issue by Implementist** [jerryscript-project/jerryscript#2914]
As the title suggests, the testcase is:
```
var func = function (number) {
    "use strict";
    number.snippetText = "";
};
func(-334918463);
```
The defination and assignment at the third line leads to an exception when I run this testcase in V8 and SpiderMonkey. But Jerry doesn't throws any exception.

**Comment by rerobika** [comment]
@Implementist Thanks for the report I think it is a valid bug, since I've found the corresponding part of the standard for that special case.

https://www.ecma-international.org/ecma-262/5.1/#sec-8.7
```
The object that may be created in step 1 is not accessible outside of the above method.
An implementation might choose to avoid the actual creation of that transient object.
The only situations where such an actual property assignment that uses this internal
method can have visible effect are when it either invokes an accessor function
or is in violation of a Throw predicated error check. When Throw is true any property
assignment that would create a new property on the transient object throws an error.
```

Do you have any fix for this issue or are you planning to open a PR for this problem? (Ofc, it is only optional.)

**Comment by Implementist** [comment]
Thanks for your reply. I have no idea about how to fix this at present.

**Comment by rerobika** [comment]
@Implementist No problem I'll take a look at it.

**Comment by galpeter** [comment]
@rerobika I've done a bit of debugging and created this: https://github.com/galpeter/jerryscript/commit/d3f6254e856a0053baf84f96c63bee919179e38c  however I think it is only a partial fix.
