### ISSUE TITLE
jerryscript.net - invalid SSL certificate

### ISSUE THREAD

**Issue by trivikr** [jerryscript-project/jerryscript#2924]
### Steps to reproduce
https://jerryscript.net/ shows invalid SSL certificate
This issue was noticed while adding link to JerryScript in OpenJSF CPC README in https://github.com/openjs-foundation/cross-project-council/pull/218 

### Expected output
The website https://jerryscript.net/ loads without any certificate issues

### Actual output
https://jerryscript.net/ shows invalid SSL certificate

**Comment by trivikr** [comment]
Any update on this request?

**Comment by akosthekiss** [comment]
@trivikr Thanks for reporting this issue. It seems that it is related to outdated IP addresses (https://help.github.com/en/articles/troubleshooting-custom-domains#https-errors). We have let our DNS maintainers know about it, let's hope for a fix soon.

**Comment by trivikr** [comment]
Any update on this request?

**Comment by akosthekiss** [comment]
It's expected to get solved in some days.

**Comment by akosthekiss** [comment]
The issue has been solved. Our GH pages work OK over https.
