### ISSUE TITLE
Set type

### ISSUE THREAD

**Issue by cup** [jerryscript-project/jerryscript#3169]
Another issue says that "Set" has been implemented, but it hasnt:

~~~
$ ./jerry
jerry> Set
Script Error: ReferenceError
jerry> Set()
Script Error: ReferenceError
jerry> new Set()
Script Error: ReferenceError
~~~

**Comment by cup** [comment]
https://github.com/jerryscript-project/jerryscript/issues/2745

**Comment by akosthekiss** [comment]
How did you build jerry? (Command line options to build.py or cmake?)

**Comment by cup** [comment]
https://ci.appveyor.com/project/jerryscript-project/jerryscript

**Comment by akosthekiss** [comment]
Then you have certainly seen the line in the logs: "JERRY_PROFILE                  es5.1". You'll have to configure and build the project for your own needs (es2015-subset profile, as it seems in this case). Closing as invalid.

**Comment by cup** [comment]
~~~
./tools/build.py --profile=es2015-subset
~~~
