### ISSUE TITLE
Method Number.prototype.toPrecision does not meet ES5.1

### ISSUE THREAD

**Issue by YaoHouyou** [jerryscript-project/jerryscript#3173]
### JerryScript revision
[9ab4872](https://github.com/jerryscript-project/jerryscript/commit/9ab48722445c483a2b984fef609d13ab87894dea)

### Build platform
`Ubuntu 16.04.6 LTS (Linux 4.15.0-55-generic x86_64)`

### Build steps
```
python tools/build.py --debug --logging=on --line-info=on --error-messages=on --cpointer-32bit=on --mem-heap=2048 --profile=es2015-subset
```

### Test case
````
var NISLFuzzingFunc = function(d, c) {
    var a = d.toPrecision(c);
};
var NISLParameter0 = 59246;
var NISLParameter1 = function(p) {
};
NISLFuzzingFunc(NISLParameter0, NISLParameter1);
````

### Execution steps
````
./jerryscript/build/bin/jerry testcase.js
````

### Output
````
````

### Expected behavior
Throw RangeError on line 2;
`RangeError: toPrecision argument must be between 1 and 21`

### Description:
I have manually calculated the test case above according to the definition of `Number.prototype.toPrecision` in the ES5.1. I think that jerryscript should throw RangeError exception in [step 8](http://www.ecma-international.org/ecma-262/5.1/index.html#sec-15.7.4.7).
```
8. If p < 1 or p > 21, throw a RangeError exception.
```
So, I suspect it is a bug of jerry.

**Comment by rerobika** [comment]
@YaoHouyou Thanks for the report the issue seems valid.
