### ISSUE TITLE
An issue about Object.getOwnPropertySymbols

### ISSUE THREAD

**Issue by YuanWangC** [jerryscript-project/jerryscript#3380]
The method `Object.getOwnPropertySymbols` has its Initial definition in ES6. 
According to ES6, the argument will be processed by `ToObject`. It‘s not appropriate to throw an error if argument is not an object.
###### JerryScript version
[996bf76](https://github.com/jerryscript-project/jerryscript/commit/996bf76f5956c65342c1726d3f629fbea41320ab)
###### Build steps
```
python tools/build.py --clean --logging=on --line-info=on --error-messages=on --cpointer-32bit=on --mem-heap=1572864 --profile=es2015-subset
```
###### Test case
```
var NISLFuzzingFunc = function() {
    var p = true;
    Object.getOwnPropertySymbols(p);
};
NISLFuzzingFunc();
```
###### Command
`jerryscript/build/bin/jerry testcase.js`
###### Output
`Script Error: TypeError: Argument is not an object.`

**Comment by dbatyai** [comment]
This has been fixed recently in 3bf2bc5.
