### ISSUE TITLE
SyntaxError: Lexical declaration cannot appear in a single-statement context

### ISSUE THREAD

**Issue by YuanWangC** [jerryscript-project/jerryscript#3381]
When I execute the testcase below, jerryscript throw an error `SyntaxError: Lexical declaration cannot appear in a single-statement context`, but other engines (v8, Chakra, spiderMonkey etc.) did not throw exceptions. Is this an issue of jerryscript?
###### JerryScript version
[996bf76](https://github.com/jerryscript-project/jerryscript/commit/996bf76f5956c65342c1726d3f629fbea41320ab)
###### Build steps
```
python tools/build.py --clean --logging=on --line-info=on --error-messages=on --cpointer-32bit=on --mem-heap=1572864 --profile=es2015-subset
```
###### Test case
```
var NISLFuzzingFunc = function() {
    a: function f(){return true;}
};
NISLFuzzingFunc();
```
###### Command
`jerryscript/build/bin/jerry testcase.js`
###### Output
`SyntaxError: Lexical declaration cannot appear in a single-statement context.`

**Comment by zherczeg** [comment]
Looks like. For whatever reason `{ a: let a; }` is a syntax error, and we have worked on these recently.  All constructs follows the same rule except function, which can appear in `if-else`. And now you found that it is true for labelled as well. Don't worry this is a trvial fix. @rerobika are you interested?
