### ISSUE TITLE
A question of Assignment

### ISSUE THREAD

**Issue by zhangle1987** [jerryscript-project/jerryscript#3477]
when execute this case on the other engines can be run success, but jerryscript throws exception:Script Error: ReferenceError
expression like this:

`var _ref;
var args = [1];
function Root() {

}

function _p(arg1, arg2) {
  return arg1 ? arg1 : arg2;
}

//success
var temp = (_ref = Object.getPrototypeOf(Root)).call({});
var constructor = _p(this,temp);

// fail on jerryscript
var constructor = _p(this,
  (_ref = Object.getPrototypeOf(Root)).call({})
);`

**Comment by zherczeg** [comment]
I asked in #3473, but do you interested to work on these?

**Comment by rerobika** [comment]
@zherczeg IMO #3473 has nothing in common with this issue. The problem is the wrong opcode combining during the argument list parsing.
