### ISSUE TITLE
const variable prompt undefined

### ISSUE THREAD

**Issue by crud-boy** [jerryscript-project/jerryscript#3561]
###### JerryScript revision
v2.2.0 5fdeb7c

###### Build platform
win10 for x64

###### Build steps
1. open cmake gui
2. configure vs2019 compilation target win32
3. change "JERRY_PROFILE" to "es2015-subset"
3. open project and build debug version

###### Build log
success

###### Test case
no

###### Execution platform
win32

###### Execution steps
1. open jerry.exe
2. input "const a = new Uint8Array([1,2,3])"
3. input "a"

###### Output
```
jerry> const a = new Uint8Array([1,2,3])
undefined
jerry> a
```
###### Backtrace
```
  0: <eval>:1
Script Error: ReferenceError: a is not defined
```

###### Expected behavior
1,2,3

###### Other problems
Why the console prompts undefined, I have turned on all options in cmake-gui, including jerry-logging, jerry-debugger, jerry-error_message, then how to load the extension containing the console function

**Comment by rerobika** [comment]
Hi @crud-boy!

https://github.com/jerryscript-project/jerryscript/pull/3558 is going to resolve this problem. Please take an other try when it gets merged.
