### ISSUE TITLE
resource_name is undefined when executing from a snapshot

### ISSUE THREAD

**Issue by Hexxeh** [jerryscript-project/jerryscript#3577]
When building with `JERRY_LINE_INFO` enabled, generating and executing a snapshot seems to ignore the `resource_name` argument provided to `jerry_generate_snapshot_with_args`, meaning that when you attempt to get a backtrace, one is never available.

**Comment by rerobika** [comment]
This issue is going to be resolved by #3745.

**Comment by rerobika** [comment]
Resolved via #3745 .
