### ISSUE TITLE
Map.forEach omits newly added elements

### ISSUE THREAD

**Issue by rwalczyna** [jerryscript-project/jerryscript#3592]
As stated in [ES6 23.1.3.5](https://www.ecma-international.org/ecma-262/6.0/#sec-map.prototype.foreach), elements added after the call to __forEach__  begins should be visited. 
So new element added in callback needs to be visited after _old_ elements.

###### Test code:
```js
var map = new Map;
map.set('a', 1);
map.set('b', 2);
var l = 0;
map.forEach(function(value, key) {
  print(key, value);
  if(l === 0) {
    map.set('c', 3);
  }
  l++;
});
print("Loops:", l);
```
###### Output:
```
a 1
b 2
Loops: 2
```
###### Expected Output:
```
a 1
b 2
c 3
Loops: 3
```

I have checked current implementation and it looks like list of the properties' names is gathered at the beginning of execution and used till the end.
I think there should be some check after each callback execution, which would update properties' list.
The problem is in optimal implementation of this function - properties are stored in reversed singly linked list - new elements are added at the beginning (these elements should be listed at the end of foreach).

Something like internal iterator for collection object would be helpful, but this requires invalidating properties and deleting them not directly but a bit later by GC. But this needs a bit of additional memory for each collection's property and will be time consuming.

Is there any special reason why property list is reversed? Is this for optimization of adding new properties or it affects also implementations of other functions?

**Comment by rtakacs** [comment]
@rwalczyna yes, this is a well known issue why Map - Set - WeakSet and WeakMap are not ECMA6 compliant. I've started to rework the collections so that will be a solution for this issue.
