### ISSUE TITLE
Adding 'length' property to bound function

### ISSUE THREAD

**Issue by clover2123** [jerryscript-project/jerryscript#3615]
Hello,
I'm going to implement 'length' property of bound function.
I think that there are 2 approaches as belows.

1) Adding 'length' property when each bound function generated
This approach is simple but all bound function objects always hold 'length' property whether it is really used or not.

2) Lazily insert 'length' property
Adding 'length' property when it is accessed for the first time. This approach could save memory, but we should hold the length of target function when each bound function is generated. 
From the standard [es6 19.2.3.2](https://www.ecma-international.org/ecma-262/6.0/#sec-function.prototype.bind), 'length' property of bound function is calculated using the length of target function and its number of arguments.
number of arguments is already stored in `ecma_extended_object_t::u::bound_function::args_len_or_this`, but the length of target function is not.
```js
var foo = function (x,y) {};
var bound1 = foo.bind(null);
delete foo.length;
var bound2 = foo.bind(null);
print(bound1.length); // 2 (length property is defined when bound function is generated)
print(bound2.length); // 0
```
From the above case, we even cannot calculate the length property lazily because the length value of target function could be changed before the moment.
To resolve this issue, I'm considering storing the length value of target function into additional space outside the `ecma_extended_object_t` by allocating a one-slot bigger ecma_extended_object_t using `ecma_create_object()` when creating a bound function object.
Intialization of length property could be marked by pointer with tag (jmem_cpointer_tag_t) which is similar to the case of function object.

Which one do you prefer?

**Comment by rerobika** [comment]
Hi @clover2123 !

I'd definitely prefer the second solution due to the lazy instantiation. You can create an `ecma_bound_function_object_t` with an extended object header and a uint32_t length structure member. As I see this change does not affect the ES5.1 profile, so in this case the `ecma_bound_function_object_t` could remain a `ecma_extended_object_t`.
