### ISSUE TITLE
A question about creating arrays.

### ISSUE THREAD

**Issue by YiWen-y** [jerryscript-project/jerryscript#3650]
When running this test case blow, jerry threw an exception in line 5. Why does this happen?Is it a bug of jerry?

###### JerryScript revision
[996bf76](https://github.com/jerryscript-project/jerryscript/commit/996bf76f5956c65342c1726d3f629fbea41320ab)

###### Build platform
    Ubuntu 16.04.6 LTS (Linux 4.15.0-55-generic x86_64)

###### Build steps
    python tools/build.py --clean --debug --logging=on --line-info=on --error-messages=on --cpointer-32bit=on --mem-heap=1572864 --profile=es2015-subset

###### Test case
```
var NISLFuzzingFunc = function(u) {
     print([u = u-1, this]);
     print([this, 1]);
     print([1, u = u-1]);
     print([this, u = u-1]);
 };
 var NISLParameter0 = 2;
 NISLFuzzingFunc(NISLParameter0);

```

###### Execution steps
    build/bin/jerry testcase.js

###### Output
```
1, [object Object]
[object Object], 1
1, 0
Exception backtrace:
    0: testcase.js:5
    1: testcase.js:8
Script Error: ReferenceError: Undefined reference.
```
###### Expected behavior
```
1, [object Object]
[object Object], 1
1, 0
[object Object], -1
```

**Comment by rerobika** [comment]
@YiWen-y Thanks for the report, this is the side effect of #3594, I've submitted a PR to resolve this problem.
