### ISSUE TITLE
Nominating Csaba Osztrogonác (@ossy-szeged) to become a JerryScript committer

### ISSUE THREAD

**Issue by dbatyai** [jerryscript-project/jerryscript#3757]
I would like to nominate Csaba Osztrogonác (@ossy-szeged) to become a committer. He already has >50 merged pull request, with several contributions to the test infrastructure and windows support, among others.

https://github.com/jerryscript-project/jerryscript/pulls?q=is%3Apr+author%3Aossy-szeged+is%3Aclosed

**Comment by akosthekiss** [comment]
+1

**Comment by rerobika** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by rtakacs** [comment]
+1

**Comment by akosthekiss** [comment]
Five seconds and no objections. Congrats to our new committer, @ossy-szeged !
