### ISSUE TITLE
Nominating Szilagyi Adam (@szilagyiadam) to become a JerryScript committer

### ISSUE THREAD

**Issue by dbatyai** [jerryscript-project/jerryscript#3758]
I would like to nominate Szilagyi Adam (@szilagyiadam) to become a committer. He already has >80 merged pull request, with lots of contributions towards implementing new EcmaScript features.

https://github.com/jerryscript-project/jerryscript/pulls?q=is%3Apr+is%3Aclosed+author%3Aszilagyiadam

**Comment by akosthekiss** [comment]
+1

**Comment by rerobika** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by rtakacs** [comment]
+1

**Comment by akosthekiss** [comment]
Five seconds and no objections. Congrats to our new committer, @szilagyiadam !
