### ISSUE TITLE
Incorrect await behavior?

### ISSUE THREAD

**Issue by zealotds** [jerryscript-project/jerryscript#3894]
###### JerryScript revision
commit: cae6cd08fb3dc8d2ded58177f997f8e3b3747b28

###### Build platform
Debian GNU/Linux 10 (buster) (Linux 4.19.0-8-amd64 x86_64)

###### Build steps
`python tools/build.py --profile=es2015-subset`

###### Test case
Run following code with the CLI bin/jerry:
```
async function foo (promise) { let v = await promise; print('value:', v); }
let r = null
let bar = new Promise(resolver => r = resolver)
foo(bar)
```

###### Output
`value: [object Promise]`

###### Expected behavior
It should not print until `r('some value')`

**Comment by zherczeg** [comment]
Await has not been implemented yet, currently a nop. I am working on the implementation.

**Comment by clarkttfu** [comment]
Looking forward to it so much! Hope to hear you soon 👍

**Comment by zealotds** [comment]
Looking forward to it so much! Hope to hear you soon 👍

**Comment by clarkttfu** [comment]
Excellent !!
