### ISSUE TITLE
An issue about RegExp Assertions

### ISSUE THREAD

**Issue by NWU-NISL** [jerryscript-project/jerryscript#3914]
According to the usage of `^`, the `/^A/` will match the beginning of the string. But jerry matches the character that is not at the beginning of the string. When executing this testcase on other engines, (like chakraCore, v8, and spiderMonkey) I get the expected output.  

#### version

`996bf76`

#### testcase

```javascript
var NISLFuzzingFunc = function(){
    var a = "anA".split(/^A/);
    print(a);
};
NISLFuzzingFunc();
```

#### output

```
an,
```

#### expected output

```
anA
```

Contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by galpeter** [comment]
@NWU-NISL @YuanWangC Please update your JerryScript repository. The git has mentioned is from 2019 November.

This issue is already fixed, and can't be reproduced on the current master. (closing as Fixed)
