### ISSUE TITLE
An issue about JSON.stringify

### ISSUE THREAD

**Issue by NWU-NISL** [jerryscript-project/jerryscript#3926]
When executing the testcase below, the result when the second argument of `JSON.stringify` is `[]` is different from when the parameter is a non-empty array. According to the ES6.0, the expected output should be `{}`. And when executing this testcase on other engines, (like chakraCore, v8, and spiderMonkey) I get the expected output.  This may be an issue about `JSON.stringify`.

#### version

`bd1c4df`

#### testcase

```javascript
var NISLFuzzingFunc = function (nislMutationParameter0, nislMutationParameter1, nislMutationParameter2) {
        return JSON.stringify(nislMutationParameter0, nislMutationParameter1, nislMutationParameter2);
};

var nislMutationArgument0 = {"4664":false,"18836":true};
var nislMutationArgument1 = [];
var nislMutationArgument2 = "abc";
var NISLCallingResult = NISLFuzzingFunc(nislMutationArgument0, nislMutationArgument1, nislMutationArgument2);
print(NISLCallingResult);
```

#### output

```
{
abc“4664":false,
abc”18836":true
}
```

#### expected output

```
{}
```

Contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by akosthekiss** [comment]
Disclaimer: The issue report may or may not be valid, I haven't checked. But. According to `git rev-list --count bd1c4df..master`, the reported revision is 104 commits older than master at the time of writing my comment. Please, _do_ update your local copy more frequently!
