### ISSUE TITLE
an issue about DataView constructor

### ISSUE THREAD

**Issue by NWU-NISL** [jerryscript-project/jerryscript#3927]
When executing the testcase below, jerry throws a RangeError when the third argument is present and the value is undefined. According to ES6.0, the expected output should be 0. The value of [[ByteLength]] internal slot may not satisfy the spec. This is an issue about DataView constructor.

#### version

`bd1c4df`

#### testcase

```javascript
var NISLFuzzingFunc = function(){
    var a = DataView(new ArrayBuffer(256),0,undefined);
    print(a.getInt16(0));
};
var result = NISLFuzzingFunc();
```

#### output

```
RangeError: Start offset is outside the bounds of the buffer.
```

#### expected output

```
0
```

Contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by akosthekiss** [comment]
Disclaimer: The issue report may or may not be valid, I haven't checked. But. According to `git rev-list --count bd1c4df..master`, the reported revision is 104 commits older than master at the time of writing my comment. Please, _do_ update your local copy more frequently!
