### ISSUE TITLE
Date.setFullYear works incorrectly

### ISSUE THREAD

**Issue by godmiaozi** [jerryscript-project/jerryscript#3973]
after calling Date.setFullYear interface, the date object returns incorrect day numbers

###### JerryScript revision
2.1

###### Build platform
Ubuntu 18.04.3 LTS

###### unexpected behavior
```diff
jerry> date = new Date("1960-11-19");
+ Sat Nov 19 1960 08:00:00 GMT+08:00
jerry> date.setFullYear(1961)
 -256262400000
jerry> date
- Sat Nov 18 1961 08:00:00 GMT+08:00
```

**Comment by ossy-szeged** [comment]
I can confirm it is still valid on master if timezone is not UTC.

**Comment by godmiaozi** [comment]
@ossy-szeged any plan to fix it ?

**Comment by ossy-szeged** [comment]
> @ossy-szeged any plan to fix it ?
Yes, I assigned the issue to myself and will fix soon.

**Comment by godmiaozi** [comment]
@ossy-szeged many thanks...
