### ISSUE TITLE
Question about jerry_json_parse() encoding

### ISSUE THREAD

**Issue by clarkttfu** [jerryscript-project/jerryscript#4160]
###### JerryScript revision
Identify the git hash(es) or tag(s) where the issue was observed.
2.4.0 (b828d1c1)

Hi there,

Does  `jerry_json_parse()` only accept 'cesu-8' string?
Because emoji chars like '🌝'  (<Buffer f0 9f 8c 9d>) might crash the process in my tests.

If only 'cesu-8' is supported, it will be great to add another `jerry_json_parse_from_utf8()`.

Thanks,
Clark

**Comment by rerobika** [comment]
Hi @clarkttfu!

That's a good catch we are going to fix it soon!

**Comment by rerobika** [comment]
After #4186 both UTF8 and CESU8 strings are accepted.
