### ISSUE TITLE
Using 32 bits float and -Wconversion

### ISSUE THREAD

**Issue by philippe44** [jerryscript-project/jerryscript#4183]
I'm a bit puzzled as what happens when using 32 bits float (-DJERRY_NUMBER_TYPE_FLOAT64=0) in various places like line 350 of ecma-helpers-conversion.c (and few other places). By default, when using GCC (I'm porting to the esp32 platform, so it's gcc), the root CMakeLists.txt set "conversion" as a warning and an error but obviously, 
```
num = num * radix + (ecma_number_t) digit_value;
```
Produces an error as we are trying to represent a 32 bits int into a 4 bytes float, so we loose precision. I surely can change CMakeLists.txt or the code itself, but is there any preferred way before I submit my port?

**Comment by ossy-szeged** [comment]
In this case it's safe to cast radix to ecma_number_t, because it can be only 2, 8 or 16,
Unfortunately it seems there are other build failures related to -DJERRY_NUMBER_TYPE_FLOAT64=0.

**Comment by dbatyai** [comment]
Preferably these should be fixed in the code itself, and only disable warnings if absolutely necessary.

**Comment by philippe44** [comment]
ok, done in the code, was just a few casts
