### ISSUE TITLE
A question about RegExp syntax

### ISSUE THREAD

**Issue by NWU-NISL** [jerryscript-project/jerryscript#4192]
According to ES6.0, the syntax *CharacterEscape*  is extented at Annex B. *LegacyOctalEscapeSequence* is added in  *CharacterEscape*. So the output of the tescase below is `/\04/`. And other engines (like V8, Chakracore, spiderMonkey) also give an output `/\04/`. Is this an issue of jerry? Or did I miss any information about this?

#### version

```
bd1c4df
```

#### command

```
jerryscript/build/bin/jerry testcase.js
```

#### testcase

```javascript
var v = function(){
    return new RegExp("\\04");
};
var result = v();
print(result);
```

#### output

```
SynaxError: RegExp escape pattern error.
```

#### expected output

```
/\04/
```

contributor:[@YuanWangC](https://github.com/YuanWangC)

**Comment by ossy-szeged** [comment]
It works as expected long long time ago, I think since 8f76a1f38223cce4cf64064fc1b67670e1f4b806 (May 26)
