### ISSUE TITLE
Date interface returns date without timezone offset on windows platform 

### ISSUE THREAD

**Issue by godmiaozi** [jerryscript-project/jerryscript#4240]
Date interface works fine on ubuntu, but not on windows platform
# on ubuntu
```
jerry> var a = new Date()
undefined
jerry> a
Sun Sep 27 2020 11:08:36 GMT+0800
```

# windows platform
```
jerry> var a = new Date()
undefined
jerry> a
Sun Sep 27 2020 03:10:05 GMT+00:00
jerry>
```

**Comment by ossy-szeged** [comment]
Timezone handling should work fine on Windows too a year ago. (And it works for me locally.)
2b3faf683d5f78e696ad97999b761b53f3fed0ae implemented it and was included in 2.1.0 release.

If you still see this issue on the latest JerryScript, please tell us your JerryScript version (release or GIT hash),
details about your OS environment (OS version, local timezone, etc.)

**Comment by ossy-szeged** [comment]
@godmiaozi Can you confirm if it works for you too?

**Comment by godmiaozi** [comment]
@ossy-szeged 
Thanks for your reply and sorry for reply you so late. I have figured out why it does not work for me. I'm using MINGW to cross compile jerry, which tries to compile the windows compatible executable from linux platform. In this case, MINGW does not define the macro `_WINDOWS`, so the Date interface does not work correctly on my side. But it seems that  `_WIN32` is defined by MINGW. i don't know whether it is better for jerry  to switch from `_WINDOWS` to `_WIN32` or not.

**Comment by ossy-szeged** [comment]
@godmiaozi: Thanks for the investigation, I got it. Fix is coming soon.

**Comment by rerobika** [comment]
@ossy-szeged What is the progress on this error?

**Comment by ossy-szeged** [comment]
> @ossy-szeged What is the progress on this error?

Ah, I forgot it, thanks for the ping. I'll prepare the PR.
