### ISSUE TITLE
Assertion 'ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDDATA || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_VIRTUAL' in ecma_is_property_writable

### ISSUE THREAD

**Issue by owl337** [jerryscript-project/jerryscript#4405]
###### JerryScript revision
2faafa4
###### Build platform
Ubuntu 18.04.5 LTS(Linux 4.15.0-119-generic x86_64)

###### Build steps
···
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g --strip=off \
--system-allocator=on --logging=on --linker-flag=-fuse-ld=gold \
--error-messages=on --profile=es2015-subset  --builddir=$PWD/build
···
###### Test case
···
var count = "0000";
var arr = Math.cos;
function func(val) {
    if (count++ > 300)
        return;
    try { arr = new Float32Array([Symbol('a'), 1]);
    } catch(e) {}
    arr[i] = -1;
    try { Object.setPrototypeOf(arr, new Int8Array(arr)); } catch(e) {}
}

for (var i=0; i<10; i ++) {
    func(new Proxy(func, []));
}

···

###### Output
···
ICE: Assertion 'ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDDATA || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_VIRTUAL' failed at /root/jerryscript/jerry-core/ecma/base/ecma-helpers.c(ecma_is_property_writable):1035.
Error: ERR_FAILED_INTERNAL_ASSERTION
Aborted

···
Credits: Found by chong from OWL337.

**Comment by rerobika** [comment]
Minimal testcase:

```js
var arr = [1];

var ta = new Int8Array(arr);
Object.setPrototypeOf(arr, ta);

arr[1] = 2;
ta = new Int8Array(arr);
Object.setPrototypeOf(arr, ta);

```
