### ISSUE TITLE
Nominating Csaba Osztrogonác (@ossy-szeged) to become a JerryScript reviewer

### ISSUE THREAD

**Issue by akosthekiss** [jerryscript-project/jerryscript#4435]
I would like to nominate Csaba Osztrogonác to become a JerryScript reviewer. I trust him to follow our processes. He has already given 50+ informal reviews and other valuable inputs:

#4395
#4388
#4381
#4330
#4329
#4317
#4296
#4288
#4278
#4256
#4253
#4247
#4246
#4230
#4226
#4223
#4181
#4172
#4153
#4152
#4145
#4140
#4102
#4086
#4084
#4035
#4026
#4007
#3981
#3967
#3949
#3942
#3925
#3915
#3912
#3907
#3906
#3900
#3879
#3838
#3792
#3742
#3617
#3598
#3576
#3567
#3496
#3338
#3318
#3224
#3146

Seconds are welcome.

**Comment by rerobika** [comment]
+1

**Comment by rtakacs** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by LaszloLango** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by dbatyai** [comment]
+1

**Comment by akosthekiss** [comment]
7 days have passed with no objections and 6 seconds. Congrats to our new reviewer @ossy-szeged !
