### ISSUE TITLE
Test262-esnext failed with debug version of jerryscript

### ISSUE THREAD

**Issue by lygstate** [jerryscript-project/jerryscript#4455]
###### JerryScript revision
3193e6d0dcd5459319bc3d50b7529ec17345a4b3

Refer to
https://github.com/lygstate/jerryscript/runs/1690866286?check_suite_focus=true

Refer to

https://github.com/jerryscript-project/jerryscript/pull/4456

**Comment by ossy-szeged** [comment]
There are few known assertions, that's why we haven't enabled debug test262 previously.
We can enable if the following issues are fixed:
- #4150
- #4446
- https://github.com/jerryscript-project/jerryscript/pull/4373#discussion_r556146023

**Comment by ossy-szeged** [comment]
Already fixed, now tests pass in debug mode and tested by CI.
