### ISSUE TITLE
A possible performance problems of repeated array creation

### ISSUE THREAD

**Issue by YaoHouyou** [jerryscript-project/jerryscript#4628]
#### Description 
When I repeatedly create a longer Array object with a length less than or equal to 131071, the execution time of the Jerryscript engine is much longer than the execution time of other engines.

#### Version

[edd2f20](https://github.com/jerryscript-project/jerryscript/commit/edd2f203974acc9ddfbad9998c29bdc40ccc0719)

#### Testcase

```javascript
var NISLFuzzingFunc = function(){
	for(var INDEX = 0; INDEX < 10000; INDEX++){
		var a = new Array(131071);
	}
};
NISLFuzzingFunc();
```

#### Execution time

```
JerryScript: 2686ms 
XS(Similar to jerryscript): 49 ms
duktape: 34ms 
quickJS:  17ms
MuJS:  19ms
hermes:  23ms
```
#### Buid
```
python2 tools/build.py --clean --logging=on --line-info=on --error-messages=on --cpointer-32bit=on --mem-heap=1572864 --profile=es2015-subset
```

#### cpu

```
Intel(R) Core(TM) i9-9940X CPU @ 3.30GHz
```

**Comment by rerobika** [comment]
Hi!

This test matches the current fast-array allocation limit, that's why it takes so long. I was also planning to optimize this part, so that's good opportunity to handle this issue.
