### ISSUE TITLE
Possible typo in feature macro

### ISSUE THREAD

**Issue by ConsciousCode** [jerryscript-project/jerryscript#4648]
I've been reading the source code to get an insight on the engine's internals and noticed a unique typo in a feature macro. Running a global search on the repo, it appears consistently across all files it's used in so it's mostly harmless, but a possible source of bugs in the future if someone tries to fix it, or if an end-user wants to disable it for some reason.

It appears as: JERRY_PROPRETY_HASHMAP
It should be: JERRY_PROPERTY_HASHMAP
It appears in 14 files, mostly in /ecma/base. No files reference the correct spelling, so it won't have affected functionality up to this point.

**Comment by rerobika** [comment]
Hi @ConsciousCode! Thanks for the report, indeed that's a typo. Feel free to open a PR with the renaming if you would like to contribute to the project.
