### ISSUE TITLE
Nominating Takács Roland (@rtakacs) to become a JerryScript committer

### ISSUE THREAD

**Issue by robertsipka** [jerryscript-project/jerryscript#4844]
He has non-trivial patches (several of them are target-specific), which can be viewed here:
https://github.com/jerryscript-project/jerryscript/pulls?q=is%3Apr+is%3Aclosed+author%3Artakacs+

Any seconds?

**Comment by rerobika** [comment]
+1

**Comment by ossy-szeged** [comment]
+1

**Comment by szilagyiadam** [comment]
+ 1

**Comment by akosthekiss** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by bzsolt** [comment]
+1

**Comment by akosthekiss** [comment]
6 seconds and no objections. Congrats to our new committer!
