### ISSUE TITLE
How to evaluate the heap and stack size needed by my project?

### ISSUE THREAD

**Issue by Sherry0901** [jerryscript-project/jerryscript#5011]
Hi!
I am using jerryscript in my project.
I need to evaluate the memory resources required by my application in order to adjust the hardware resources.
Can jerry calculate and show the heap size needed by running a JS file?

**Comment by zherczeg** [comment]
Yes. There is a `jerry_heap_stats` API in jerryscript.h. You can also pass `--mem-stats on` to the command line interpreter to check the values.

**Comment by Sherry0901** [comment]
Thanks a lot! That's what I need.
