### ISSUE TITLE
import symbol conflicts with global variable name

### ISSUE THREAD

**Issue by dananderson** [jerryscript-project/jerryscript#5015]
###### JerryScript revision
2.4.0

###### Build platform
all

###### Build steps
n/a

###### Build log
n/a

###### Test case
Assume there is a global variable named 'process' in the current realm. Assume the process package exports default and a symbol named process as well.

When using a default import:

    import process from 'process'

When using a named import: 

    import { process } from 'process'

Both statements fail.

###### Execution platform
all

###### Execution steps
n/a

###### Output
Error message: Imported binding shadows local variable

###### Backtrace
n/a

###### Expected behavior
No parse or runtime Error.

**Comment by zherczeg** [comment]
It looks like this is a "feature" in JerryScript. Probabyl something was misunderstood. Attempting to change this in #5023

**Comment by zherczeg** [comment]
Patch landed. Thank you for the report.
