### ISSUE TITLE
A question about supported ES version

### ISSUE THREAD

**Issue by SadCPPCoder** [jerryscript-project/jerryscript#5027]
Hi owners of jerryscript,

I can see the JerryScript fully supports for ES5.1, but I found it also supports many features of ES6.
So, I wonder is there any list for JerryScript to present how many features does it support for ES6?

Thanks for your great work!

**Comment by SadCPPCoder** [comment]
Thanks a lot for your confirmation.

**Comment by ossy-szeged** [comment]
You can see feature support of JerryScript here:
https://kangax.github.io/compat-table/es6/ - JerryScript 2.4 - 96%
https://kangax.github.io/compat-table/es2016plus/ - JerryScript 2.4 - 54%
( note: master JerryScript supports more es2016+ features, approximately 80+ % )
