### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [jerryscript-project/jerryscript#5124]
👋 it has been couple of years since last release in 2021, would be good to make a new release including all the recent changes, thanks!

**Comment by alex1891** [comment]
is here anybody still maintaining this project?

**Comment by alex1891** [comment]
> The pace is not that fast nowadays, but the maintainers are here, yes.

"pace is not that fast" is good, no release since 2021 and a ton of vulnerabilities

**Comment by akosthekiss** [comment]
Sarcasm. Duly noted.

Any contribution from anyone willing to spend their resources on fixing those issues faster is warmly welcome.

(BTW, Hacktoberfest is still on. Happy to put the hacktoberfest-accepted label on any quality PR.)

**Comment by alex1891** [comment]
the thing is, the issues are fixed because of the greate OSS community - what is missing is a tag for a release :)

**Comment by zherczeg** [comment]
Is there a product which need this release? Where do you want to use it?

**Comment by alex1891** [comment]
> Is there a product which need this release? Where do you want to use it?

Yes, we are using it in an commerical HMI software.

**Comment by alex1891** [comment]
so are there any plans for an release?

**Comment by ossy-szeged** [comment]
> so are there any plans for a release?
Yes, we are planning it, hopefully we will manage to release 3.0.0 this year.

**Comment by LaszloLango** [comment]
JerryScript 3.0 is officially released, https://github.com/jerryscript-project/jerryscript/releases/tag/v3.0.0
