### ISSUE TITLE
Online API reference docs doesn't match github's.

### ISSUE THREAD

**Issue by ludfjig** [jerryscript-project/jerryscript#5125]
It seems the api documentation on github and on jerryscript.net are out of sync. For example: You can find documentaiton for `jerry_call` here https://github.com/jerryscript-project/jerryscript/blob/master/docs/02.API-REFERENCE.md#jerry_call, but this function is nowhere to be found on https://jerryscript.net/api-reference/. There are other examples as well.

**Comment by bzsolt** [comment]
Thanks for the report! I've updated the webpage in #5127
