### ISSUE TITLE
Primary Contacts / Maintainers For Jerryscript?

### ISSUE THREAD

**Issue by bensternthal** [jerryscript-project/jerryscript#5158]
Hi Folks!

I work for the OpenJS foundation and we are in the process of updating our contact lists for projects. I've tried to reach out the "owner" on file for JerryScript but have been unable to reach them.

Can you let me know who the current primary maintainers are of the project are?

Many thanks!!

Ben

**Comment by akosthekiss** [comment]
Hi @bensternthal , the most active maintainers are @zherczeg and myself (@akosthekiss) at the moment.

**Comment by bensternthal** [comment]
@akosthekiss Thanks for responding! Would you be able to email me (bsternthal@linuxfoundation.org) both your email addresses?

**Comment by akosthekiss** [comment]
Sure, sent.
