### ISSUE TITLE
Nominating Gergő Csizi (@gergocs) to become a JerryScript committer

### ISSUE THREAD

**Issue by robertsipka** [jerryscript-project/jerryscript#5162]
He has several patches which can be viewed here:
https://github.com/jerryscript-project/jerryscript/pulls?q=is%3Apr+is%3Aclosed+author%3Agergocs+

Any seconds?

**Comment by LaszloLango** [comment]
+1

**Comment by rtakacs** [comment]
+1

**Comment by zherczeg** [comment]
+1

**Comment by ossy-szeged** [comment]
+1

**Comment by lygstate** [comment]
I also have patches get merged

https://github.com/jerryscript-project/jerryscript/pulls?q=is%3Apr+is%3Aclosed+author%3Alygstate+

Any change to become a JerryScript committer?

**Comment by LaszloLango** [comment]
@lygstate you can find the details of how to become a committer in the following wiki page, https://github.com/jerryscript-project/jerryscript/wiki/Governance

**Comment by akosthekiss** [comment]
4 seconds and no objections. Congrats to our new committer!
